version: "3.3"

################
### Services ###
################
services:

  #####################
  ### Test database ###
  #####################
  db:
    image: mariadb
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
